const products = [
  {
    id: 1,
    title: "hex head wood screw",
    price: 120,
    quantity: 78000,
    img: "Hexheadwoodscrew.jpg",
    description: "hex head wood screw",
  },
  {
    id: 2,
    title: "construction flat head screw",
    price: 50,
    quantity: 93000,
    img: "Constructionflatheadscrew.jpg",
    description: "construction flat head screw",
  },
  {
    id: 3,
    title:
      "universal hammer driven fastener with metal pin - short expansion zone",
    price: 900,
    quantity: 74000,
    img: "Universalhammerdrivenfastenerwithmetalpinshortepansionzone.jpg",
    description:
      "universal hammer driven fastener with metal pin - short expansion zone",
  },
  {
    id: 4,
    title: "black phosphate drywall screw",
    price: 390,
    quantity: 78000,
    img: "Blackphosphatedrywallscrew.jpg",
    description: "black phosphate drywall screw",
  },
  {
    id: 5,
    title: "Frame fastener with hex head screw",
    price: 670,
    quantity: 973000,
    img: "Framefastenerwithhexheadscrew.jpg",
    description: "Frame fastener with hex head screw",
  },
  {
    id: 6,
    title: "Self-drilling screw with EPDM washer",
    price: 420,
    quantity: 8900,
    img: "SelfdrillingscrewwithEPDMwasher.jpg",
    description: "Self-drilling screw with EPDM washer",
  },
  {
    id: 7,
    title: "Plastic nylon sleeve with spikes",
    price: 600,
    quantity: 1600,
    img: "plasticnylonsleevewithspikes.jpg",
    description: "Plastic nylon sleeve with spikes",
  },
  {
    id: 8,
    title: "Wash basin fixing kit",
    price: 504,
    quantity: 700,
    img: "washbasinfixingkit.jpg",
    description: "Wash basin fixing kit",
  },
  {
    id: 9,
    title: "Wide flat washers",
    price: 502,
    quantity: 980,
    img: "wideflatwashers.jpg",
    description: "Wide flat washers",
  },
  {
    id: 10,
    title: "Frame mounting fastener",
    price: 344,
    quantity: 1890,
    img: "framemountingfastener.jpg",
    description: "Frame mounting fastener",
  },
  {
    id: 11,
    title: "Flange head self-drilling screw",
    price: 943,
    quantity: 10990,
    img: "flangeheadselfdrillingscrew.jpg",
    description: "Flange head self-drilling screw",
  },
  {
    id: 12,
    title: "Drywall to wood screw",
    price: 673,
    quantity: 10990,
    img: "drywalltowoodscrew.jpg",
    description: "Drywall to wood screw",
  },
  {
    id: 13,
    title: "Concrete frame screw with flat head",
    price: 549,
    quantity: 1030,
    img: "concreteframescrewwithflathead.jpg",
    description: "Concrete frame screw with flat head",
  },
  {
    id: 14,
    title: "Screw for exotic hardwood",
    price: 937,
    quantity: 89990,
    img: "screwforexotichardwood.jpg",
    description: "Screw for exotic hardwood	",
  },
  {
    id: 15,
    title: "Self-drilling screw for timber to steel fixings	",
    price: 513,
    quantity: 109320,
    img: "selfdrillingscrewfortimbertosteelfixings.jpg",
    description: "	Self-drilling screw for timber to steel fixings	",
  },
];

export default products;
